=== International-Slackline-Association/slackline-data/scripts/validation/jsonSchemas/isaMembers.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "email": {
        "anyOf": [
          {
            "type": "string",
            "format": "email"
          },
          {
            "type": "string",
            "maxLength": 0
          }
        ]
      },
      "country": {
        "type": "string",
        "pattern": "^[A-Z]{2}$"
      },
      "memberType": {
        "type": "string",
        "enum": ["active", "observer", "partner", "associate"]
      },
      "infoUrl": {
        "type": "string",
        "format": "uri"
      },
      "groupId": {
        "type": "string",
        "minLength": 7,
        "maxLength": 7
      },
      "profilePictureUrl": {
        "type": "string",
        "format": "uri"
      }
    },
    "required": ["name", "email", "country", "memberType"],
    "additionalProperties": false
  }
}

=== International-Slackline-Association/slackline-data/data/communities/isa/members.json
[
  {
    "name": "International Slackline Association - ISA",
    "email": "info@slacklineinternational.org",
    "country": "CH",
    "memberType": "active",
    "infoUrl": "https://slacklineinternational.org/",
    "groupId": "YpNb23_"
  },
  {
    "name": "Slackline Verband austria",
    "email": "info@slacklineverband.com",
    "country": "AT",
    "memberType": "active",
    "infoUrl": "https://slacklineverband.com/",
    "groupId": "6lgHBQK"
  },
  {
    "name": "Slackline U.S.",
    "email": "info@slackline.us",
    "country": "US",
    "memberType": "active",
    "infoUrl": "https://slackline.us/",
    "groupId": "itHEe7U"
  },
  {
    "name": "Swiss Slackline",
    "email": "info@swiss-slackline.ch",
    "country": "CH",
    "memberType": "active",
    "infoUrl": "https://swiss-slackline.ch/",
    "groupId": "M21SOVj"
  },
   {
    "name": "AFS - Association Française de Slackline",
    "email": "augustin.moinat@gmail.com",
    "country": "FR",
    "memberType": "active",
    "infoUrl": "https://www.instagram.com/associationfrancaise_slackline/",
    "groupId": "_A0IX-u"
  },
   {
    "name": "Federacion Argentina de Slackline - FAS",
    "email": "fas.slackline@gmail.com",
    "country": "AR",
    "memberType": "active",
    "infoUrl": "https://www.instagram.com/fas.slackline/",
    "groupId": "wyTFBD2"
  },
  {
    "name": "Deutscher Slacklineverband e.V.",
    "email": "info@deutscherslacklineverband.org",
    "country": "DE",
    "memberType": "active",
    "infoUrl": "https://deutscherslacklineverband.org/",
    "groupId": "sdpUacw"
  },
  {
    "name": "Federación de Slackline Chile - Feslach",
    "email": "federacionslacklinechile@gmail.com",
    "country": "CL",
    "memberType": "active",
    "groupId": "-B2edMV"
  },
  {
    "name": "Canadian Slackline Association",
    "email": "slacklinecanada@gmail.com",
    "country": "CA",
    "memberType": "associate",
    "groupId": "Zsx7W2D"
  },
  {
    "name": "Iran Slackline",
    "email": "iranslackline@gmail.com",
    "country": "IR",
    "memberType": "associate",
    "groupId": "4cYLFoC"
  },
  {
    "name": "Slackline Dernegi",
    "email": "info@slackline.org.tr",
    "country": "TR",
    "memberType": "active",
    "infoUrl": "https://slackline.org.tr/",
    "groupId": "Y1coFqr"
  },
  {
    "name": "Japan Slackline Federation",
    "email": "info@jsfed.jp",
    "country": "JP",
    "memberType": "active",
    "infoUrl": "https://jsfed.jp/",
    "groupId": "oYr9BsN"
  },
  {
    "name": "SlackNED",
    "email": "info@slackned.nl",
    "country": "NL",
    "memberType": "active",
    "infoUrl": "https://slackned.nl/",
    "groupId": "91oL8WX"
  },
  {
    "name": "Australian Slacklining Association Inc.",
    "email": "info@slacklining.org.au",
    "country": "AU",
    "memberType": "active",
    "infoUrl": "https://slacklining.org.au/",
    "groupId": "-KXQ2Cp"
  },
  {
    "name": "Czech Slackline Association",
    "email": "info@ceska-asociace-slackline.cz",
    "country": "CZ",
    "memberType": "active",
    "infoUrl": "https://ceska-asociace-slackline.cz/",
    "groupId": "vgxi7jN"
  },
  {
    "name": "Slackline Finland",
    "email": "slackline.finland.ry@gmail.com",
    "country": "FI",
    "memberType": "associate",
    "groupId": "SGb6rCp"
  },
  {
    "name": "SlacklineLV",
    "email": "slacklinelv@gmail.com",
    "country": "LT",
    "memberType": "active",
    "groupId": "_gWv0QE"
  },
  {
    "name": "Slackline Lietuva",
    "email": "info@alternatyviai.lt",
    "country": "LV",
    "memberType": "associate",
    "infoUrl": "https://alternatyviai.lt/",
    "groupId": "X445ynp"
  },
  {
    "name": "Slackline INDIA",
    "email": "indianslacklineorg@gmail.com",
    "country": "IN",
    "memberType": "associate",
    "groupId": "WKVBMAm"
  },
  {
    "name": "Asociación Mexicana de Slackline",
    "email": "info@slackline.org.mx",
    "country": "MX",
    "memberType": "active",
    "infoUrl": "https://slackline.org.mx/",
    "groupId": "opHJmff"
  },
  {
    "name": "The UK Slackline Club",
    "email": "admin@ukslacklineclub.com",
    "country": "GB",
    "memberType": "active",
    "infoUrl": "https://ukslacklineclub.com/",
    "groupId": "AEQ0QGQ"
  },
  {
    "name": "Step Slackliners Armenia",
    "email": "stepslacklinersarmenia@gmail.com",
    "country": "AM",
    "memberType": "associate",
    "groupId": "0MBeRo3"
  },
  {
    "name": "Slovak Slackline Association ",
    "email": "Info@slacklineslovakia.sk",
    "country": "SK",
    "memberType": "active",
    "infoUrl": "https://slacklineslovakia.sk/",
    "groupId": "CoTyLJc"
  },
  {
    "name": "ASER Asociación de Slackline y Equilibrio Rosario",
    "email": "aserslackline@gmail.com",
    "country": "AR",
    "memberType": "observer",
    "groupId": "UU7eFi6"
  },
  {
    "name": "Basel City Slackliners",
    "email": "Info@baselcityslackliners.com",
    "country": "CH",
    "memberType": "observer",
    "infoUrl": "https://baselcityslackliners.com/",
    "groupId": "oDUQNBU"
  },
  {
    "name": "BeSlack",
    "email": "info@beslack.be",
    "country": "BE",
    "memberType": "observer",
    "infoUrl": "https://beslack.be/",
    "groupId": "TzwooLu"
  },
  {
    "name": "Heustock Bern",
    "email": "heustockbern@gmail.com",
    "country": "CH",
    "memberType": "observer",
    "groupId": "hogXx1Q"
  },
  {
    "name": "Jura Slack",
    "email": "juraslack.ch@gmail.com",
    "country": "CH",
    "memberType": "observer",
    "groupId": "wtkvZSL"
  },
  {
    "name": "Larmichettes Bules",
    "email": "larmichettescrew@gmail.com",
    "country": "CH",
    "memberType": "observer",
    "groupId": "Y-Cx3eu"
  },
  {
    "name": "Move Copenhagen",
    "email": "mail@movecph.com",
    "country": "DK",
    "memberType": "observer",
    "infoUrl": "https://movecph.com/",
    "groupId": "X-aAHYm"
  },
  {
    "name": "Move Moleson (The Highline Extreme)",
    "email": "thehighlineextreme@gmail.com",
    "country": "CH",
    "memberType": "observer",
    "groupId": "EL6hhEI"
  },
  {
    "name": "Move Switzerland (Bern Moves)",
    "email": "info@bernmoves.com",
    "country": "CH",
    "memberType": "observer",
    "infoUrl": "https://bernmoves.com/",
    "groupId": "aM4MSyf"
  },
  {
    "name": "Pushing panda",
    "email": "dadenk.mulyana@gmail.com",
    "country": "ID",
    "memberType": "observer",
    "groupId": "rQ8vf_R"
  },
  {
    "name": "Slack is Goudes",
    "email": "slackisgoudes@gmail.com",
    "country": "FR",
    "memberType": "observer",
    "groupId": "8_FRD2U"
  },
  {
    "name": "Slack Vitality Balsthal",
    "email": "info.slackvitality@gmail.com",
    "country": "CH",
    "memberType": "observer",
    "groupId": "6hfQLE_"
  },
  {
    "name": "Slack4fun",
    "email": "info@slack4fun.ch",
    "country": "CH",
    "memberType": "observer",
    "infoUrl": "https://slack4fun.ch/",
    "groupId": "KTvMUqn"
  },
  {
    "name": "Slackattack - Slackline Crew Bern",
    "email": "info@slackattack.ch",
    "country": "CH",
    "memberType": "observer",
    "infoUrl": "https://slackattack.ch/",
    "groupId": "eEL9eqK"
  },
  {
    "name": "LakeLiners Biel/Bienne",
    "email": "lakeliners.biel.bienne@gmail.com",
    "country": "CH",
    "memberType": "observer",
    "groupId": "aohN9ui"
  },
  {
    "name": "Slackicimes",
    "email": "slackicimes@gmail.com",
    "country": "FR",
    "memberType": "observer",
    "groupId": "_Eu7RdK"
  },
  {
    "name": "Slacklife Merida",
    "email": "slacklifemerida@gmail.com",
    "country": "MX",
    "memberType": "observer",
    "groupId": "WAHlOeL"
  },
  {
    "name": "Slackline Berlin e.V.",
    "email": "slacklineverein.berlin@gmail.com",
    "country": "DE",
    "memberType": "observer",
    "groupId": "P_x1VmM"
  },
  {
    "name": "Slackline Dresden e.V.",
    "email": "info@slackline-dresden.de",
    "country": "DE",
    "memberType": "observer",
    "infoUrl": "https://slackline-dresden.de/",
    "groupId": "CHRKCD8"
  },
  {
    "name": "Slackline Genève",
    "email": "associationslacklinegeneve@gmail.com",
    "country": "CH",
    "memberType": "observer",
    "groupId": "j2qCndy"
  },
  {
    "name": "Slackline Hamburg e.V.",
    "email": "hallo@slackline-hamburg.org",
    "country": "DE",
    "memberType": "observer",
    "infoUrl": "https://slackline-hamburg.org/",
    "groupId": "sE8n9Y0"
  },
  {
    "name": "Slackline Salzburg",
    "email": "verein@slackline-salzburg.at",
    "country": "AT",
    "memberType": "observer",
    "infoUrl": "https://slackline-salzburg.at/",
    "groupId": "cxySuPl"
  },
  {
    "name": "Slackline Stuttgart e.V.",
    "email": "slackline.stuttgart@gmail.com",
    "country": "DE",
    "memberType": "observer",
    "groupId": "M8EJZPf"
  },
  {
    "name": "Slackline Valais",
    "email": "info@slackline-valais.ch",
    "country": "CH",
    "memberType": "observer",
    "infoUrl": "https://slackline-valais.ch/",
    "groupId": "Nj2o4dB"
  },
  {
    "name": "Slackline Vorarlberg",
    "email": "info@slackline-vorarlberg.net",
    "country": "AT",
    "memberType": "observer",
    "infoUrl": "https://slackline-vorarlberg.net/",
    "groupId": "VpVPLGN"
  },
  {
    "name": "Slackline Weisslingen",
    "email": "rolf.boss@meta-bau.ch",
    "country": "CH",
    "memberType": "observer",
    "infoUrl": "https://meta-bau.ch/",
    "groupId": "WbOxezI"
  },
  {
    "name": "slackline.at",
    "email": "vorstand@slackline.at",
    "country": "AT",
    "memberType": "observer",
    "infoUrl": "https://slackline.at/",
    "groupId": "xj8P7OR"
  },
  {
    "name": "SlackLiner Halle e.V.",
    "email": "slackliner.halle@gmail.com",
    "country": "DE",
    "memberType": "observer",
    "groupId": "1yd3iGe"
  },
  {
    "name": "Slacklining Bremen e.V.",
    "email": "slackline.bremenev@gmail.com",
    "country": "DE",
    "memberType": "observer",
    "groupId": "NXEyVKf"
  },
  {
    "name": "Slacklions Zürich",
    "email": "slackline.zurich@gmail.com",
